### ISSUE TITLE
mmap 錯誤是什麼問題

### ISSUE THREAD

**Issue by geshihuazhong** [vearch/gamma#23]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4bd006]

goroutine 1 [running]:
golang.org/x/exp/mmap.(*ReaderAt).ReadAt(0x0, 0xc000a8a000, 0x800, 0x800, 0x0, 0xc000a88000, 0x4, 0x8)
	/root/GOPATH/src/golang.org/x/exp/mmap/mmap_unix.go:66 +0x26
main.BatchAddDocToEngine(0x186a0)
	/root/GOPATH/gamma/go/examples/test.go:222 +0x675
main.Add()
	/root/GOPATH/gamma/go/examples/test.go:279 +0x5dc
main.main()
	/root/GOPATH/gamma/go/examples/test.go:347 +0xf2

**Comment by wxingda** [comment]
请发下gamma.log
