### ISSUE TITLE
test_files.cc相关问题疑惑

### ISSUE THREAD

**Issue by rrjia** [vearch/gamma#32]
1、c++接口中只有createTable，没有删除表的操作，请问应该如何删除表格？
2、GetDocByID，GetDocByDocID这两个接口中ID是一个string，但是实际内部是一个int，docID和id有什么区别呢？而且以id=1进行调用时
string docid = "1";
GetDocByID(opt.engine, docid.c_str(), docid.size(), &doc_str, &doc_str_len);
却没有查询到任何doc
3、当索引类型设置为倒排乘积量化，把index_size设为1000时，当表中完全写入10000条数据后，进行查询时每次都是返回-2错误码，显示索引没有训练，当强制搜索时，也经常搜索不到任何结果

**Comment by zcdb** [comment]
此问题在其它issue中已经解答，所以关掉此issue.
