### ISSUE TITLE
等了一个月也没人回

### ISSUE THREAD

**Issue by rrjia** [vearch/gamma#38]
1、c++接口中只有createTable，没有删除表的操作，请问应该如何删除表格？
2、GetDocByID，GetDocByDocID这两个接口中ID是一个string，但是实际内部是一个int，docID和id有什么区别呢？而且以id=1进行调用时
string docid = "1";
GetDocByID(opt.engine, docid.c_str(), docid.size(), &doc_str, &doc_str_len);
却没有查询到任何doc
3、当索引类型设置为倒排乘积量化，把index_size设为1000时，当表中完全写入10000条数据后，进行查询时每次都是返回-2错误码，显示索引没有训练，当强制搜索时，也经常搜索不到任何结果

**Comment by zcdb** [comment]
1.有个Close接口
2.GetDocByID这个接口指通过_id（即主键）来获取，实际上_id会对应一个docid，其中docid是从0开始的递增序列，GetDocByDocID就是用docid来获取
3.第三个需要更详细的信息，如果可以的话请贴一下gamma.log

**Comment by zcdb** [comment]
另外这边可能没有vearch活跃，也可以去vearch社区提issue

**Comment by rrjia** [comment]
[gamma.log](https://github.com/vearch/gamma/files/5922632/gamma.log)

**Comment by rrjia** [comment]
1、close接口使engine层级的，也就是说close()方法调用后整个引擎的所有的表都会被删除吧？

**Comment by rrjia** [comment]
谢谢解答：
但是我按照你的回答，在
test::Create();
test::Add();  
后 使用GetDocByID这个接口指通过_id（即主键）来获取doc，没有获得任何结果

std::string data = "10";
int len =  data.size();   

// 存储结果的 
char *doc_str;
int doc_len; 

int ret = GetDocByID(test::opt.engine, (char *)(data.c_str()), len, &doc_str, &doc_len);

tig_gamma::Doc doc;
doc.Deserialize(doc_str, doc_len);

**Comment by zcdb** [comment]
> 1、close接口使engine层级的，也就是说close()方法调用后整个引擎的所有的表都会被删除吧？

对于gamma来说，一个engine对应一张表

**Comment by zcdb** [comment]
> 谢谢解答：
> 但是我按照你的回答，在
> test::Create();
> test::Add();
> 后 使用GetDocByID这个接口指通过_id（即主键）来获取doc，没有获得任何结果
> 
> std::string data = "10";
> int len = data.size();
> 
> // 存储结果的
> char *doc_str;
> int doc_len;
> 
> int ret = GetDocByID(test::opt.engine, (char *)(data.c_str()), len, &doc_str, &doc_len);
> 
> tig_gamma::Doc doc;
> doc.Deserialize(doc_str, doc_len);

这个问题，从你给的gamma.log来看，实际上你插入的数据都失败了，所以前面无法搜索，也无法通过接口获取数据

**Comment by rrjia** [comment]
sorry，之前的gamma.log是错误的日志，真实的情况是数据写入成功了，附件是最新的gamma.log，非常感谢

[Uploading gamma.log…]()

**Comment by rrjia** [comment]
[gamma.log](https://github.com/vearch/gamma/files/5924234/gamma.log)

**Comment by zcdb** [comment]
你插入数据的时候_id是什么样的呢？有“10”这个值吗？另外你插入的数据看样子比较少，没有达到建索引的标准，所以搜索不出来结果

**Comment by rrjia** [comment]
有的，我就是使用readme中 profile_10k.txt中的数据

0	0.jpg	1315	1342	9728
1	1.jpg	1315	1342	9740
2	2.jpg	15248	15249	15252
3	3.jpg	1318	2628	12137
4	4.jpg	1672	2599	5266
5	5.jpg	1318	12102	9767
6	6.jpg	1620	11158	11163
7	7.jpg	6728	6745	14918
8	8.jpg	1315	1342	1349
9	9.jpg	1315	1345	1371
10	10.jpg	6728	6745	11953

_id 就是第一列的数字
在test.h中
fields_vec = {"_id", "img", "field1", "field2", "field3"};
fields_type = {tig_gamma::DataType::STRING, tig_gamma::DataType::STRING,
               tig_gamma::DataType::STRING, tig_gamma::DataType::INT,
               tig_gamma::DataType::INT};

**Comment by zcdb** [comment]
看日志有报错信息ERROR 2021-02-04 16:29:12,440 gamma_doc.cc:43 engine is null
所以取不出来数据，你修改了test_file.cc是吧，可以确认一下用法

**Comment by rrjia** [comment]
我也注意到这个error了，但是我通过debug调试engine地址是有值的，不是null

**Comment by zcdb** [comment]
那就奇怪了，可以贴一下你修改后的test_file.cc和test.h吗？

**Comment by rrjia** [comment]
发现错误原因了，这个engie=null 是doc.Deserialize(doc_str, doc_len);  触发的，在doc.Deserialize(doc_str, doc_len);  要加一行这样的代码：
```

  tig_gamma::Doc doc;
  doc.SetEngine(static_cast<tig_gamma::GammaEngine *>(opt.engine));
  doc.Deserialize(doc_str, doc_len);  
```

**Comment by zcdb** [comment]
好的。对了，其它几个相关issue可以关一下吗？实在抱歉，这个的确是之前没有关注到这边的issue，如果要提issue的话还是vearch那边会活跃一点

**Comment by rrjia** [comment]
好的，那我去vearch那边提吧
