### ISSUE TITLE
ids 查询会先过滤么

### ISSUE THREAD

**Issue by chenchuangc** [vearch/gamma#67]
您好，我想用vearch来做粗排，对召回率和响应要求都比较高
请求的样例类似
```
curl -H "content-type: application/json" -XPOST -d'
{
  "query": {
    "sum": [
      {
        "field": "field_name",
        "feature": [
          0.1,
          0.2,
          0.3,
          0.4,
          0.5
        ],
        "min_score": 0.9,
        "boost": 0.5
      }
    ],
    "ids": [
      "id1",
      "id2"，"xxxx"
    ]
  }
}

````
ids大概是1w个，麻烦问一下，
1. 我这样查询可以么
2. 索引的类型是否应该选择flat呢
3. 查询的过程是先按照id获取再计算相似度，还是先召回再过滤id呢

我看之前有一个QA写的过程好像是先做向量召回，在召回的中间进行term过滤，如果是这样的话用flat是不是就变成了遍历
[QA地址](https://github-wiki-see.page/m/vearch/vearch/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
![image](https://user-images.githubusercontent.com/13183268/133049362-b01e562b-1d02-4b69-bb7e-3a33b8f85a3e.png)

```

**Comment by wxingda** [comment]
1. 可以
2. 可以试下flat的性能
3. range index是先过滤，后做向量计算，不会变成遍历
